version: '2'

services:
    web:
        restart: always
        build: ./ahsite
        volumes:
            - /usr/src/www
        command: uwsgi --ini uwsgi.ini
        env_file: ./config/prod/web.env

    http:
        restart: always
        build: ./nginx
        ports:
            - "80:80"
        volumes_from:
            - web
